// Generated by CoffeeScript 2.3.2
(function() {
  var assert, converter;

  assert = require('assert');

  converter = require('../english-converter');

  describe('English number translator', function() {
    it('should validate input', function() {
      assert.equal(converter.validateInteger('23.11'), false);
      assert.equal(converter.validateInteger(''), false);
      assert.equal(converter.validateInteger('0'), true);
      assert.equal(converter.validateInteger('-0'), false);
      assert.equal(converter.validateInteger('00'), false);
      assert.equal(converter.validateInteger('22056776543455097645624346540'), true);
      assert.equal(converter.validateInteger('-50'), true);
      return assert.equal(converter.validateInteger('000x0!@'), false);
    });
    describe('addSpace', function() {
      return it('should only add space to non empty string without space at the end', function() {
        assert.equal(converter.addSpace(''), '');
        assert.equal(converter.addSpace('test '), 'test ');
        return assert.equal(converter.addSpace('test'), 'test ');
      });
    });
    describe('getParts', function() {
      it('should split string into three digit parts', function() {
        var parts;
        parts = converter.getParts('945688764');
        assert.equal(parts.length, 3);
        assert.equal(parts[0], '945');
        assert.equal(parts[1], '688');
        return assert.equal(parts[2], '764');
      });
      it('should allow first part to be two digits', function() {
        var parts;
        parts = converter.getParts('45688');
        assert.equal(parts.length, 2);
        assert.equal(parts[0], '45');
        return assert.equal(parts[1], '688');
      });
      return it('should allow first part to be one digit', function() {
        var parts;
        parts = converter.getParts('4568');
        assert.equal(parts.length, 2);
        assert.equal(parts[0], '4');
        return assert.equal(parts[1], '568');
      });
    });
    describe('translatePart', function() {
      it('should ignore zero', function() {
        return assert.equal(converter.translatePart('0'), '');
      });
      it('should translate irregular numbers < 20', function() {
        assert.equal(converter.translatePart('1'), 'one');
        assert.equal(converter.translatePart('2'), 'two');
        assert.equal(converter.translatePart('3'), 'three');
        assert.equal(converter.translatePart('4'), 'four');
        assert.equal(converter.translatePart('5'), 'five');
        assert.equal(converter.translatePart('6'), 'six');
        assert.equal(converter.translatePart('7'), 'seven');
        assert.equal(converter.translatePart('8'), 'eight');
        assert.equal(converter.translatePart('9'), 'nine');
        assert.equal(converter.translatePart('10'), 'ten');
        assert.equal(converter.translatePart('11'), 'eleven');
        assert.equal(converter.translatePart('12'), 'twelve');
        assert.equal(converter.translatePart('13'), 'thirteen');
        assert.equal(converter.translatePart('14'), 'fourteen');
        assert.equal(converter.translatePart('15'), 'fifteen');
        assert.equal(converter.translatePart('16'), 'sixteen');
        assert.equal(converter.translatePart('17'), 'seventeen');
        assert.equal(converter.translatePart('18'), 'eighteen');
        return assert.equal(converter.translatePart('19'), 'nineteen');
      });
      it('should ignore leading zeroes', function() {
        assert.equal(converter.translatePart('019'), 'nineteen');
        assert.equal(converter.translatePart('009'), 'nine');
        assert.equal(converter.translatePart('000'), '');
        return assert.equal(converter.translatePart('000000000'), '');
      });
      return it('should translate hundreds', function() {
        var useAnd;
        useAnd = true;
        assert.equal(converter.translatePart('101', useAnd), 'one hundred and one');
        assert.equal(converter.translatePart('111', useAnd), 'one hundred and eleven');
        assert.equal(converter.translatePart('130', useAnd), 'one hundred and thirty');
        assert.equal(converter.translatePart('935', useAnd), 'nine hundred and thirty five');
        return assert.equal(converter.translatePart('500', useAnd), 'five hundred');
      });
    });
    return describe('translate', function() {
      it('should translate zero', function() {
        return assert.equal(converter.translate('0'), 'Zero');
      });
      it('should capitalize first letter', function() {
        return assert.equal(converter.translate('101'), 'One hundred and one');
      });
      it('should add word "negative" if number has minus sign', function() {
        return assert.equal(converter.translate('-53465'), 'Negative fifty three thousand four hundred and sixty five');
      });
      it('should join parts with correct numbers', function() {
        assert.equal(converter.translate('101000'), 'One hundred one thousand');
        assert.equal(converter.translate('101001'), 'One hundred one thousand and one');
        assert.equal(converter.translate('120567'), 'One hundred twenty thousand five hundred and sixty seven');
        assert.equal(converter.translate('246012'), 'Two hundred forty six thousand and twelve');
        assert.equal(converter.translate('56123456'), 'Fifty six million one hundred twenty three thousand four hundred and fifty six');
        assert.equal(converter.translate('1001000'), 'One million one thousand');
        assert.equal(converter.translate('1001001000'), 'One billion one million one thousand');
        assert.equal(converter.translate('1001001001000'), 'One trillion one billion one million one thousand');
        return assert.equal(converter.translate('1001001001001000'), 'One quadrillion one trillion one billion one million one thousand');
      });
      return it('should correctly handle empty parts', function() {
        return assert.equal(converter.translate('1000000000'), 'One billion');
      });
    });
  });

}).call(this);
